### ISSUE TITLE
Update relm4-components for the new component trait

### ISSUE THREAD

**Issue by AaronErhardt** [Relm4/Relm4#101]
It'd be nice to support relm4-components in 0.5 from day one. These are the currently available components:

- [ ] open_button
- [ ] alert
- [ ] open_dialog
- [ ] save_dialog

And of course, more reusable components are always welcome!

**Comment by cofee-on-the-desk** [comment]
I'd like to work on this issue.

**Comment by AaronErhardt** [comment]
Awesome! Let me know if you need any help.

**Comment by euclio** [comment]
How are the components expected to access their parent? By passing it through `InitParams`?

**Comment by AaronErhardt** [comment]
Yes, the new component design makes them independent from their parent unless they require specific `InitParams` to access the parent. You can also forward the `Output` of the child to the `Input` of the parent.
