### ISSUE TITLE
Make tokio optional / allow different runtimes

### ISSUE THREAD

**Issue by AaronErhardt** [Relm4/Relm4#114]
Because of the (incredibly annoying) async comparability issue there might be some interest to use other runtimes that tokio. Potentially, defaulting to glib might be useful to reduce dependencies.

> Of course, this needs a proper evaluation, but I wanted to add this as a reminder for the 0.5 milestone.

**Comment by mmstick** [comment]
Flume would then be a necessary channel alternative. They just recently fixed a major bug that made me avoid it for all things async (messages received out of order), so now it's a viable async+sync alternative.

**Comment by mmstick** [comment]
GLib doesn't have a good way to set up a multi-threaded async runtime. It'd require essentially building your own runtime from scratch. But we could use use [smolscale](https://github.com/geph-official/smolscale) or other async-task-based runtimes as an alternatives to tokio.

**Comment by AaronErhardt** [comment]
Either way, I think we should separate this part from the relm4 crate. Maybe there's already a crate that abstracts async runtimes nicely with feature flags and if not it shouldn't be complicated to write one ourselves.

**Comment by AaronErhardt** [comment]
Maybe we can use this crate: https://lib.rs/crates/async_executors

It doesn't seem to support glib yet, but at least the abstractions are already there.

**Comment by sdroege** [comment]
I think making this configurable is going to increase complexity a lot and you'd have to often ask in issues which configuration people are actually using.

It probably makes more sense to decide on a single thing and let people figure out cross-runtime compatibility themselves. As Relm is already message-passing-based, working with other runtimes is not really a problem if you're aware of the problem (-> documentation).

**Comment by AaronErhardt** [comment]
Of course you can always just create your own runtime, but this is built-in. You just send a future to execute a command and it will be handled by a runtime in the background: https://github.com/Relm4/Relm4/blob/next/examples/progress.rs#L123

You can send messages that pass the commands from there to your own runtime but that's not really optimal IMO. And if there was only one runtime to choose, I'd opt for tokio because it simply is the best supported runtime available.

**Comment by AaronErhardt** [comment]
This does not seem to be of interest for anyone and most async crates won't work without tokio anyway, so I'm closing this for now.
