### ISSUE TITLE
Improve `pre_view` and `post_view` for 0.5

### ISSUE THREAD

**Issue by AaronErhardt** [Relm4/Relm4#136]
+ Current problem: IIFEs used in `pre_view` and `post_view` don't allow you to make use of local variables in `watch!` etc.
+ Just removing the IIFEs will make `return` skip the update logic when used in `pre_view`

### My suggestion

Change the codegen to this:

```rust
struct DoNotReturnManually;
let view_code: fn(args...) -> DoNotReturnManually = |...| {
    #pre_view
    #view code
    (|| { #post_view })();
    DoNotReturnManually
};
view_code(args...);
```

Advantages:

+ Return still possible in `post_view` where it doesn't skip the other update logic.
+ Accidental return in `pre_view` impossible because the closure returns `DoNotReturnManually`

> I still have to test if this actually works :)

**Comment by AaronErhardt** [comment]
@euclio what do you think about my suggestion?

**Comment by euclio** [comment]
I'm still not convinced that there's no desugaring that makes things work as expected. Can you share an example of the code that we want to make work?

**Comment by AaronErhardt** [comment]
I wonder if removing the IIFEs completely works too. The second IIFFs doesn't do anything anyway because it's the last statement and the first one will cause a warning about unreachable code. So you can't do anything wrong by accident.

**Comment by euclio** [comment]
I'm not sure, the original issue was that code like

```rust
fn pre_view() {
  if some_condition {
    return; // skip rest of pre_view
  }
  
  // other code
}
```

would unexpectedly and silently skip the actual view update code. I don't think a dead code warning would fire in that case?

In any case, if this is a blocker for 0.5 maybe we could disallow `return` in the macro expression entirely and add it back in a future version if we figure out a way to make it work. We should at least add a test case to the repo that demonstrates the code that isn't working with the IIFEs present.

**Comment by AaronErhardt** [comment]
I've tested the macro and it does create a warning when returning from `pre_view`. Together with `#[deny(unreachable_code)]` it even throws an error. I've added a test case that will cause an error when using IIFEs and also one as part of the doc tests that makes sure a warning is emitted: https://relm4.org/docs/next/relm4_macros/attr.component.html#notes-on-pre_view

**Comment by euclio** [comment]
Another thought I had here: what if `pre_view` and `post_view` looked like macro invocations (`pre_view! { ... }`)? That might make it more obvious that they're just being injected into the `view` function and don't act like a normal function.

**Comment by AaronErhardt** [comment]
Surely that would make it more explicit. But with the current state of rust-analyzer and IDE integration I assume the current solution yields better results...
