### ISSUE TITLE
new approach: Consider splitting `init` into `init` and `init_view`

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#144]
Simple components likely only need to implement the transform from `Self::InitParams` -> `Self`, and just use the `view_output!()` macro to construct the widgets.

If we split `init()` into `init(params: Self::InitParams) -> Self` and `init_view(&self, root: &Self::Root) -> Self::Widgets`, then we could provide a default implementation of `init_view()` that constructs the `Widgets` from `view_output!()`. That saves the user some boilerplate. It also gives us the benefit of not needing to expose a way to construct `ComponentParts` to the user.

Components that need more complex initialization could still override `init_view` as needed.

Also, feel free to name bikeshed. Maybe `init_widgets` is a better name.

**Comment by AaronErhardt** [comment]
I still have to think about this, but we might suffer from the same limitation as components. We want to keep a `Controller` in the model but that requires the component to be launched, which potentially requires widgets and we have a cyclic dependency again.

But for simple components this could be a good solution. There's already the `SimpleComponent` trait that might be a good target for implementing this idea.

**Comment by AaronErhardt** [comment]
I'm happy with the current design and 0.5 seems to have settled on one init method. Maybe for 0.6 we can optimize the initialization further but I'm closing this for now due to lack of activity.
