### ISSUE TITLE
Combine command updates with normal updates

### ISSUE THREAD

**Issue by mmstick** [Relm4/Relm4#148]
It should be possible to combine the two methods if we make an enum which can be either.

```rs
pub enum CompMsg<C: Component> {
    Cmd(C::CommandOutput),
    Input(C::Input)
}
```

```rs
fn update(
    &mut self,
    message: CompMsg<Self>,
    sender: &ComponentSender<Self>
) -> Option<Self::Command> {
    match message {
        Message::Cmd(output) => {},
        Message::Input(input) => {},
    }
}
```
The upside is that the caller doesn't have to set up additional methods. The downside is that they have to check the variant of the update. Any thoughts on this?

**Comment by AaronErhardt** [comment]
I see some potential in this because it would allow you to share code between command and normal updates more easily and eliminates yet another method. 

Yet, it could be a bit annoying to use match. Maybe `SimpleComponent` could once again help with providing a simpler API, while the `Component` trait has this syntax for more complex situations. I think that's be the best compromise, actually.

**Comment by mmstick** [comment]
I've experimented with requiring that `CommandOutput` implements `Into<Self::Input>`, but that causes difficulty with using `()` as the type for `CommandOutput`.

**Comment by AaronErhardt** [comment]
Instead of `Into<Self::Input>` I'd rather just use a single type for both input and command output. Yet the question is if this is desirable or not. At least for more complex components it's probably better to keep those separated :thinking:

**Comment by mmstick** [comment]
The challenge is that the type has to be `Send` when sent from the command thread

**Comment by mmstick** [comment]
I guess an enum could also be used to isolate internal component inputs from external user inputs.

**Comment by euclio** [comment]
> I see some potential in this because it would allow you to share code between command and normal updates more easily and eliminates yet another method.

Couldn't you just extract the shared code into a method on the struct impl?

> Yet, it could be a bit annoying to use match.

Big +1 here. I think it's a big downside, since it adds 2 levels of indentation to every update implementation.

**Comment by AaronErhardt** [comment]
I think the current API has kind of stabilised by now and this suggestion doesn't have a practical advantage. If there aren't any new thoughts on this matter I'd close this issue in a few days.

**Comment by euclio** [comment]
I do think that there's value in differentiating component-internal messages from external messages if we can find a nice API. Any component that responds to a dialog needs this, and has to rely on  `#[doc(hidden)]` for now. I don't think it's a blocker for 0.5 though.

**Comment by AaronErhardt** [comment]
This does not seem to be worth investigating further, it seems to me.
