### ISSUE TITLE
FactoryVec unable to remove widget when using ListBox.

### ISSUE THREAD

**Issue by edfloreshz** [Relm4/Relm4#168]
Relm is unable to remove widgets from a `GtkListBox` because when the user pops elements out of the model, Relm tries to remove the inner widget and not the `GtkListBoxRow`, this results in a warning: 

`Gtk-WARNING **: 03:15:30.836: Tried to remove non-child`.

This happens because Gtk inserts a [ListBoxRow](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.ListBoxRow.html) automatically between the list and the widget.

- GtkListBox
    - GtkListBoxRow (auto-added)  
        - GtkCustomWidget

**Comment by AaronErhardt** [comment]
Thanks for the report! This seems to be [fixed already](https://github.com/Relm4/Relm4/blob/next/relm4/src/factory/widgets/gtk.rs#L172) on the "next" branch thanks to the work of @cofee-on-the-desk.

If you want we can backport this fix to the current stable version.
