### ISSUE TITLE
Cannot create widgets expectedly through double layer `Factory`

### ISSUE THREAD

**Issue by lomirus** [Relm4/Relm4#180]
I am writing an chatting app, and I use the factory to generate the chat panels for each user you chat to. And in each panel, here I need to use factory again to generate the messages. Then I found there are differences between them in some methods with the same name.

![](https://i.imgur.com/EZEjpbk.png)

Here is an image from the relm-examples within the `impl Widgets<AppModel, ()> for AppWidgets`

![](https://i.imgur.com/E2tcgCZ.png)
This image is from my project within the `impl FactoryPrototype for Chatroom`.

Firstly, the `self` in the first image is an `AppWidgets`, but in the second one you need to switch it to the `widgets` parameter. This inconsistency is just okay. But secondly, which is more important, there's nothing about the sender but you have to pass it to the `generate` method.

I've heard the v0.5 is on the way and there are many rework(not sure has this one been planned), maybe we can also fix this issue in it?

**Comment by AaronErhardt** [comment]
I think this is already fixed (kind of by accident) on the "next" branch for 0.5. You can already find the docs for 0.5 here: https://relm4.org/docs/next/relm4/

**Comment by lomirus** [comment]
I have tried the v0.5, and stuck again in another problem related to this issue (or maybe just because I didn't fully understand the new version's mechanics)

Here is my code refactored in v0.5.0 (next branch):
```rust
pub struct ChatroomModel {
    pub username: String,
    pub messages: FactoryVecDeque<Box, Message, MainMsg>,
}
impl FactoryComponent<Stack, MainMsg> for ChatroomModel {
// ...
  fn init_model(
      init_params: Self::InitParams,
      _index: &DynamicIndex,
      _input: &Sender<Self::Input>,
      _output: &Sender<Self::Output>,
  ) -> Self {
      let ChatroomInitParams { username, messages: messages_src } = init_params;
      let mut messages: FactoryVecDeque<Stack, Message, MainMsg> =
          FactoryVecDeque::new(
              /* No methods to get the widget */,
              &sender.input
          );
      for i in 0..messages_src.len() {
          messages.push_back(messages_src[i]);
      }
  
      ChatroomModel { username, messages }
  }
// ...
```

To create the `ChatroomModel`, I need to create a widget (`messages_box: gtk::Box`) to show the messages first. But I cannot access any widget in the `init_model` function.

**Comment by lomirus** [comment]
If I need to set the `messages_box` as the child of the root widget, then I can only set it in `init_root()`, because other methods seem to be called every time when a message is created. However there is neither `&self` nor `model` that I can call in the `init_root()`.

**Comment by AaronErhardt** [comment]
Mhh, yes that's a problem, but that could be changed. We could supply the model to init_root.
As a workaround you could wrap you widgets in a additional Box at the root.

**Comment by AaronErhardt** [comment]
I've changed the `init_root` method. Does it work for you now?

**Comment by lomirus** [comment]
Wow, it finally works. Thanks!
