### ISSUE TITLE
Implement `first()` & `back()` for `FactoryVecDeque`

### ISSUE THREAD

**Issue by lomirus** [Relm4/Relm4#187]
[`first()`](https://doc.rust-lang.org/nightly/alloc/collections/vec_deque/struct.VecDeque.html#method.front) & [`back()`](https://doc.rust-lang.org/nightly/alloc/collections/vec_deque/struct.VecDeque.html#method.back) are all convenient methods, and they also have all been implemented for `VecDeque`. I think they are very useful when you want to push a dynamic widget depending on the first or the last element of the vector. Besides, `front_mut()` and `back_mut()` are also useful when you just want to change them instead of pushing a new one.

`get()` and `get_mut()` can be a workaround now, but sometimes they are not concise enough obviously.

**Comment by AaronErhardt** [comment]
Closed via #188
