### ISSUE TITLE
Unable to set property on nullable widget in new macro syntax

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#201]
The following code does not work in the new macro syntax:

```rust
view! {
  gtk::HeaderBar {
    set_title_widget: Some(&gtk::Box) {
      add_css_class: "linked"
    }
  }
}
```

It fails with:

```
error[E0599]: the method `add_css_class` exists for enum `std::option::Option<&_>`, but its trait bounds were not satisfied
   --> examples/components.rs:33:17
    |
33  |                 add_css_class: "linked",
    |                 ^^^^^^^^^^^^^ method cannot be called on `std::option::Option<&_>` due to unsatisfied trait bounds

```

**Comment by AaronErhardt** [comment]
The previous syntax was removed in favour of the `#[wrap(Some)]` attribute. The background for this was a discussion in the matrix room about the new conditional syntax.

Here's the main reason for removing the old syntax (later in the discussion we came up with the `wrap` attribute):

<blockquote> For the new conditional syntax of the `view!` macro there's one remaining problem. You can't write something like this:
```rust
set_center_widget = Some(match) expr { ... }
```
or
```rust
set_center_widget = Some(if) expr { 
        ...
    } else {
        ...
    }
```

At least that would look very odd and would also be huge pain to parse correctly. So I thought it makes sense to introduce an `#[optional]` attribute that does the job off wrapping the widget inside `Some(...)` during the assignment. This gave me the idea to abandon the somewhat weird (and error prone) `Some(gtk::Widget) { ... }` syntax all along in favor of attributes. 

What are your thoughts on this? Do you prefer the old syntax or do you think attributes are better?

</blockquote>

**Comment by euclio** [comment]
Ah, I see. `#[wrap(Some)]` looks fine to me.

It would be helpful to make the macro reject the `Some(widget)` syntax and instead suggest `#[wrap]`, if possible.
