### ISSUE TITLE
Communicate between components on different levels

### ISSUE THREAD

**Issue by AaronErhardt** [Relm4/Relm4#213]
### Discussed in https://github.com/Relm4/Relm4/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **Paveloom** July 18, 2022</sup>
So, imagine you have the following graph of components:

```mermaid
flowchart LR
Window --> A --> B --> C
Window --> Dialog
```

The dialog is set to be modal and transient for the parent window, so it can't be moved. However, its sole purpose is to communicate with the `C` component, so it would naturally belong as a component of the `C` component. There are basically two diametrical problems here:

1) If the graph is left as is, one should construct a channel between the two components by creating messages in *each* of the components in between: this pollutes the code of the components and leads to quite a lot of duplication.
2) If the `Dialog` component is moved to be a component of the `C` component, there is no way to make it transient for the parent window. Well, one could copy the parent window into each component (similar to the [`save_dialog`](https://github.com/Relm4/Relm4/blob/8985b76ae0ac612b63c0830fb8c6ec85327c3af2/relm4-examples/examples/save_dialog.rs) example, but saving the window into an additional field of *each* component in between), but that's just a waste of memory (also, pollutes the model of each component).

Are there nicer ways to handle either of these problems?</div>

**Comment by Paveloom** [comment]
There is also a related issue with actions. Currently, actions are supposed to be registered at the top level of the application, since they're inserted into the application window. If the `Dialog` component is moved to be a component of the `C` component, there is no (easy) way to access its sender at the top level.

A global message broker that you suggested could indeed address all of these. Something that makes all senders accessible to all components.

**Comment by cofee-on-the-desk** [comment]
To get a top-level window, you can use `WidgetExt::root` and cast it into a `gtk::Window` (Or you can use `RelmWidgetExt::toplevel_window`).

Assuming `A` and `B` are not windows, you might still be able to put `Dialog` as the component of `C`.

**Comment by Paveloom** [comment]
@cofee-on-the-desk Thanks, it seems to work (although, I wasn't able to do it without `unwrap`'s).

I didn't find the `RelmWidgetExt::toplevel_window` item, though. Where is it?

**Comment by cofee-on-the-desk** [comment]
@Paveloom it's currently on the 'next' branch and will be available when relm4 0.5 releases. If you're curious, here's how the method is defined: [link](https://github.com/Relm4/Relm4/blob/4da75941636af096d4c8a945c1e8ac8164bddb5a/relm4/src/extensions/mod.rs#L63)

**Comment by Paveloom** [comment]
@cofee-on-the-desk  Aight, I made it like this:

```rust
/// Locate the top level window this widget is attached to
fn toplevel_window(widget: &impl glib::IsA<gtk::Widget>) -> Option<adw::ApplicationWindow> {
    widget
        .ancestor(adw::ApplicationWindow::static_type())
        .and_then(|widget| widget.downcast::<adw::ApplicationWindow>().ok())
}

#[allow(clippy::missing_docs_in_private_items)]
#[relm4::widget(pub)]
impl relm4::Widgets<Model, super::Model> for Widgets {
    view! {
        dialog = gtk::Dialog {
            set_transient_for: parent!(
                #[allow(clippy::unwrap_used)]
                Some(&toplevel_window(&parent_widgets.widget).unwrap())
            ),
            // <...>
        }
        // <...>
    }
    // <...>
}
```

Not particularly pretty with the `unwrap`, but it works.

**Comment by cofee-on-the-desk** [comment]
@Paveloom I think you can just put `unwrap` inside your `toplevel_window` function so you don't have to deal with `Option`.

Anyway, are there any more use cases for communication of components on different levels?

**Comment by Paveloom** [comment]
@cofee-on-the-desk Right, thank you.

Well, I had a real case problem with dialogs as described above. I still have a problem with actions, but I will refactor them away in favor of setting up buttons manually in menus. I currently have the following pattern in my project:

```mermaid
flowchart LR
Leaflet --> A
Leaflet --> B
Leaflet --> AsyncMessageHandler
A-. 1 .-> AsyncMessageHandler
AsyncMessageHandler-. 2 .-> A
AsyncMessageHandler-. 3 .-> B
AsyncMessageHandler-. 4 .-> A
```

The components `A`,  `B`, and `C` communicate with each other, so they *need* to send messages through the leaflet. The dotted lines are to show how it would work if components could communicate directly. The numbers are the order of messages.

I can imagine someone having the following graph of components:

```mermaid
flowchart LR
A --> B --> C
A --> D --> E
```

This makes communication between `C` and `E` even more verbose.
