### ISSUE TITLE
What is the idiomatic way of using FileChooserDialog?

### ISSUE THREAD

**Issue by pkolaczk** [Relm4/Relm4#235]
I need to do a really simple thing: 
A button, when clicked, displays a modal FileChooserDialog. 
If a file gets selected, the application model receives a message with the file path. 
If user cancels the dialog, the dialog disappears and no update to the model is performed. 

I first tried to initialize the dialog inside the lambda passed to the `connect_clicked` of the button, but then I realized I cannot e.g. reference the main window of the app to be able to use in `transient_for`, due to lifetime problems. So I guess that might not be the way to go... 

Should the dialog widget be created once, stored in the AppWidgets structure and reused whenever possible? 
But if so, then where should I put the code that opens the dialog and calls its `run_async` to get the user selection? 
Does it mean I have to add another variable to my AppModel, to determine if the dialog is currently open?

**Comment by pkolaczk** [comment]
Is this approach correct:
```rust

    fn view(&mut self, model: &AppModel, sender: Sender<AppMsg>) {
        if model.state == AppState::SelectingInputPath {
            let input_path_chooser = FileChooserDialog::builder().title("Select directory")
                .modal(true)
                .transient_for(&self.window)
                .select_multiple(true)
                .build();
            input_path_chooser.add_button("Select", ResponseType::Accept);
            input_path_chooser.add_button("Cancel", ResponseType::Cancel);
            input_path_chooser.run_async(move |dialog, result | {
                match result {
                    ResponseType::Accept => send!(sender, AppMsg::AddInputPath(PathBuf::from(...))),  // todo: get the path from the dialog
                    _ =>
                        send!(sender, AppMsg::CancelSelectInputPath),
                }
                dialog.destroy();
            })
        }
    }

```

**Comment by pkolaczk** [comment]
One more thing - how do I get list of Paths from the selection? I can see `dialog.files()` returns a `ListModel`. Is there any documentation on how to deal with that and convert items to proper type (e.g. strings, or paths)?

**Comment by pkolaczk** [comment]
Actually I figured out how to directly construct the file chooser dialog inside the `connect_clicked` lambda. It turns out I can just `clone` the main window because those Gtk widgets are not really widgets, but (refcounted) references to the widgets. This looks like a very fundamental misunderstanding - would be nice if  widget semantics were explained somewhere in the beginning of the docs.

**Comment by mur4ik18** [comment]
Can I star this issue? =) 
It's very helpful, thanks a lot!
