### ISSUE TITLE
Chicken and egg problem with model and widgets in Relm4 0.5-beta 

### ISSUE THREAD

**Issue by pkolaczk** [Relm4/Relm4#237]
Your factory example initializes widgets before the model, because `FactoryVecDequeue` needs to reference the container widget:

```rust
        // Insert the macro codegen here
        let widgets = view_output!();

        let model = AppModel {
            created_widgets: counter,
            counters: FactoryVecDeque::new(widgets.counter_box.clone(), &sender.input),
        };
```

However, the simple.rs example references the model in the view! generation, and therefore it initializes the model before the view:

```rust
     let model = AppModel { counter };
     // Insert the macro code generation here
     let widgets = view_output!();
```

Now if I wanted to use ideas from both of those examples, e.g. watch a model field in the view and also use a factory - I can't.

**Comment by cofee-on-the-desk** [comment]
We could remove the `widget` parameter and use a default widget instead (e.g. `Box::default()`).

```rust
let model = AppModel {
    created_widgets: counter,
    counters: FactoryVecDeque::new(&sender.input),
};
// Insert the macro codegen here
let widgets = view_output!();
```

And in the view macro, you would write this:

```rust
append = model.counters.widget() {
    // Modify the widget
}
```

**Comment by pkolaczk** [comment]
Yeah, that makes sense. Then the view would use the model and that way it feels a lot more natural than the model referencing the view.

**Comment by AaronErhardt** [comment]
Maybe we could add a method that creates a default widget as @cofee-on-the-desk suggested. However, the more idiomatic solution would be to use the `#[local]` attribute IMO.

```rust
        let counter_box = gtk::Box::default();

        let model = AppModel {
            created_widgets: counter,
            counters: FactoryVecDeque::new(counter_box.clone(), &sender.input),
        };

        let widgets = view_output!();
```

And then in view:

```rust
    #[local]
    counter_box -> gtk::Box { ... }
```
