### ISSUE TITLE
Decouple `libadwaita` feature from main application type

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#255]
Some applicaitons may want to use Relm implementations (such as factories) on libadwaita widgets without using the libadwaita Application type. It would be nice to decouple the two, so that a savvy user could use `set_application` to use `gtk::Application` instead.

**Comment by AaronErhardt** [comment]
We could also just use `gtk::Application` in Relm4's interfaces and require users to cast when they need libadwaita's application type. There are only a few additional features in `adw::Application` so we could just downcast it to `gtk::Application` for the public interface.
