### ISSUE TITLE
Return a clone of the `DynamicIndex` after inserting a new item into a factory

### ISSUE THREAD

**Issue by Paveloom** [Relm4/Relm4#257]
I just hit a use case where I need to store dynamic indices of new items in the models of other items in the factory, but there is no way to obtain a `DynamicIndex` right now, except through a connected event. I would like to suggest to return a clone of the dynamic index in all `insert` calls. For example, a clone of the `dyn_index` here:

https://github.com/Relm4/Relm4/blob/ae761b14064ead777137637db51a60158dbf1433/relm4/src/factory/collections/vec_deque.rs#L189-L220

**Comment by AaronErhardt** [comment]
Sounds good. This would be a good first issue, but if nobody wants to pick it up, I can create a PR for it too.
