### ISSUE TITLE
Add example of optional property syntax to macro_reference example

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#263]
The [optional property syntax](https://relm4.org/book/stable/widget_macro_reference.html#assign-properties) in the `view!` macro (`optional_property?: some_value`) appears to still be supported, but we don't have an example of it anywhere in the repository. Perhaps it's less useful now that gtk-rs' methods tend to not take `Option`s anymore?

We should either add an example of it to the `macro_reference` example, or remove support for it.

**Comment by AaronErhardt** [comment]
I think it's still useful, especially if you only want to set a property under certain circumstances. It's rare to be fair, but I can imagine some reasonable use-cases.
