### ISSUE TITLE
`set_child()` vs `content_area().append()` for gtk::Dialog

### ISSUE THREAD

**Issue by N4tus** [Relm4/Relm4#274]
`RelmSetChildExt` is implemented for `gtk::Dialog` using its `set_child` method. This, however, removes the action area the dialog may have. As a result, buttons added with `add_button()` no longer appear. In my opinion it would be less surprising, if, instead of `RelmSetChildExt`, `RelmContainerExt` is implemented for `gtk::Dialog` adding each widget to the content-area of the dialog.

This would change the view macro, so that nested children would be appended to the content area of the `gtk::Dialog`. To retain the current behaviour, `set_child` must be used  manually.

I am using KDE as my desktop environment and that may effect how the dialog handles the action area.

**Comment by AaronErhardt** [comment]
Thanks for reporting this! I think you're right, this is not the expected behavior. And I'm pretty sure KDE is not the cause :)

Do you want to send a PR or should I take care of it?

**Comment by N4tus** [comment]
I have created a PR (#275) for it.
