### ISSUE TITLE
Running examples on Win11 failed

### ISSUE THREAD

**Issue by HymanZHAN** [Relm4/Relm4#332]
Hi there,

I was trying out Relm4 and wanted to see how it looks on Windows. With all dependencies installed, I could build the example app without a problem. However, running the app failed with the following message:

![image](https://user-images.githubusercontent.com/26806995/198827616-1f3e4d16-0d50-4e6d-bb16-fb3e874fce7a.png)

Is it related to some Windows-related crates? How can I fix it? Thanks!

P.S. My system: Windows 11 Professional 22H2

**Comment by AaronErhardt** [comment]
I only tried Relm4 on Windows 10 so far, but I think Windows 11 should work too.

How did you install the dependencies and which toolchain are you using?

**Comment by HymanZHAN** [comment]
I followed the steps listed here: https://gtk-rs.org/gtk4-rs/git/book/installation_windows.html
I am using the MSVC toolchain.

**Comment by AaronErhardt** [comment]
Mhh, weird. I'm not an expert regarding Windows, but maybe someone in the [gkt-rs matrix room](https://matrix.to/#/#rust:gnome.org) has some insights.

**Comment by HymanZHAN** [comment]
I think I encountered the same issue as this person: https://gist.github.com/Ep0chalypse/0e0f9ef43eb7f0218eaa8fe0822f3d36

My `harfbuzz.dll` was also loaded from Microsoft's JDK installation:

![image](https://user-images.githubusercontent.com/26806995/198872903-287cd268-2278-44a1-b039-3c6e75a71443.png)

Removing the MAUI workload from Visual Studio fixed the issue.
