### ISSUE TITLE
Asynchronous Components

### ISSUE THREAD

**Issue by edfloreshz** [Relm4/Relm4#342]
I'm working on an app that relies heavily on asynchronous operations, can that be done in Relm4?

Perhaps a new trait called `SimpleComponentAsync` could be implemented with async functions?

I'm not really sure if this is possible, therefore the issue.

**Comment by AaronErhardt** [comment]
Actually, that might be possible, I will look into that. But on the other side, components already have commands which give you pretty solid async support as well. 

Btw. there's an open PR that allows you to transform a component into a message stream with `StreamExt` etc.: https://github.com/Relm4/Relm4/pull/311

**Comment by edfloreshz** [comment]
I'll try to see if the PR solves my use case, thanks! 

Still, I think this is worth looking into, would be nice to be able to call async without using commands. 

Let me know if I can be of use.
