### ISSUE TITLE
Asynchronous Factory Components

### ISSUE THREAD

**Issue by edfloreshz** [Relm4/Relm4#346]
Since `AsyncComponent`s can have factory components in them, it makes sense to have asynchronous factory components as well.

**Comment by AaronErhardt** [comment]
Asynchronous factories are a bit more complicated and need some design decisions upfront.

For components, it's fine to have an async init function because you rarely access a component's state anyway. But for factories, it would be pretty weird to not be able to access the inner data. So either we make `init()` synchronous for the `AsyncFactoryComponent` trait or we only allow accessing the elements as `Option<Data>` where `None` means that the `init()` future is still running and `Some` means that the initialization is done.

**Comment by edfloreshz** [comment]
I think we can work with an Option, unless you think it's better the other way.

**Comment by AaronErhardt** [comment]
Actually, when looking at [`FactoryVecDeque`](https://relm4.org/docs/next/relm4/factory/collections/struct.FactoryVecDequeGuard.html) the only major change in the API would be that there would be no `Index` and `IndexMut` implementations. And another change would be that these methods would also return `None` as long as the `init_model()` future isn't completed which makes the API rather unpredictable.

 On the other side, you might argue that the regular `Vec` type also just stores data without any async initialization.

So my opinion on this matter is to leave `init_model()` synchronous unless there's a good use-case for making it async. Async initialization comes with quite a few pitfalls in the API that would make factories different from regular data collections from the standard library.

I assume you have a use-case for this, so you should be able to tell which version is better.

**Comment by edfloreshz** [comment]
I want to initialize a factory component by calling async code, my intention is that the factory displays a loading icon until the future is resolved.

**Comment by AaronErhardt** [comment]
> my intention is that the factory displays a loading icon until the future is resolved.

That won't work with plain async initialization though. It simply shows nothing until the future resolves and the widgets are generated. Yet, a solution for this could be to allow users to implement a method called `loading_widgets()` for example that immediately returns a placeholder that's replaces as soon as the future completes and the actual widgets are generated.

Alternatively, you can also store an `Option<Data>` for whatever you need to initialize and use commands to the initialization. Then in the `view` macro you could write something like this:

```rust
if let Some(data) = &model.data {
    gtk::Box {
        // Actual content
    }
} else {
    // Loading animation
    gtk::Spinner {}
}
```

**Comment by edfloreshz** [comment]
I prefer implementing a method, it's way less confusing than having an Option.

**Comment by AaronErhardt** [comment]
Alright, I'll try to give it a shot, but it might take some time (probably until the next weekend). In the meantime, you could of course try to implement it yourself. The `AsyncComponent` trait and the current factory implementation should be a good inspiration and most code can be copy-pasted from the regular factory implementation anyway.
