### ISSUE TITLE
"set_global_css" panics on tracker.rs example

### ISSUE THREAD

**Issue by geoffreyarthaud** [Relm4/Relm4#364]
On relm4 v0.5.0 beta 5, the function relm4::set_global_css panics even if it is called just after RelmApp::new(), as [explained in the doc](https://aaronerhardt.github.io/docs/relm4/relm4/fn.set_global_css.html).

Therefore, the tracker.rs example does not work

```
> cargo run --example tracker
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/examples/tracker`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', relm4/src/lib.rs:142:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
OS : Linux Pop_Os 22.04
Rust 1.64.0
Relm4 0.5.0-beta-5

Thanks a lot for this great project !

**Comment by AaronErhardt** [comment]
Thanks for the report! I've submitted a PR to address this issue: #365

Btw. the docs you're using are not up-to-date (even if it's still accurate for set_global_css). You can find recent docs [here](https://relm4.org/docs/next/relm4/fn.set_global_css.html) or on docs.rs.

**Comment by geoffreyarthaud** [comment]
Thank you for your very fast answer! And thanks for the link to the updated doc
