### ISSUE TITLE
Support for Bidirectional Data Binding

### ISSUE THREAD

**Issue by Ayush1325** [Relm4/Relm4#377]
Currently, relm4 only seems to support one-way data binding using `#[watch]`. I think this can be great when a property can be manipulated by both Rust code and Gtk GUI (eg: window size).

**Comment by AaronErhardt** [comment]
Data bindings are now released with 0.6.0-alpha.2. However, feedback is welcome since we can still change a lot of things ahead of the 0.6.0 release.
