### ISSUE TITLE
Closing any Relm4 app will lead to a segmentation fault

### ISSUE THREAD

**Issue by octavz** [Relm4/Relm4#381]
Hi, 

I am not sure what is the cause for this, I am on windows with WSL2 (Ubuntu virtualized basically) and running any Relm4 app will show a segmentation fault when closing the main window.
  
```
relm4-examples git:(main) cargo run --example tokio
   Compiling relm4-examples v0.4.0 (/home/xxx/relm4/relm4-examples)
    Finished dev [unoptimized + debuginfo] target(s) in 5.93s
     Running `/home/xxx/relm4/target/debug/examples/tokio`
[1]    23669 segmentation fault  cargo run --example tokio
```

Toolchain details:

```
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/xxx/.rustup

installed toolchains
--------------------

stable-2020-06-18-x86_64-unknown-linux-gnu
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

**Comment by AaronErhardt** [comment]
Interesting. Can you provide more information? Maybe you can run the binary with valgrind. Also, to make sure that this is actually a problem with Relm4 and not just one of our dependencies, could you please try one of the [gtk-rs](https://github.com/gtk-rs/gtk4-rs) examples?

**Comment by AaronErhardt** [comment]
Thanks for confirming. I wish you the best of luck for debugging this issue. Maybe valgrind or a debugger can help you.
