### ISSUE TITLE
Relm4 should support multiple application instances

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#396]
We currently panic if multiple instances of the same application are started:

https://github.com/Relm4/Relm4/blob/9ad0a5dabae5db0ca88ad7fa791d533c7bd32a2a/relm4/src/app.rs#L87

This is very limiting for certain classes of application (file managers, for instance). We should remove this limitation and handle this case gracefully.

**Comment by AaronErhardt** [comment]
It seems like removing the else branch with the panic solves the issue, but it doesn't open a new window. Maybe we should explore more options, but my assumption with that else branch was definitely wrong since GTK re-uses the application when you start an app twice...

**Comment by AaronErhardt** [comment]
We've addressed the first issue now, but I don't think this is all you need for fm, right?
It should be possible to select whether starting a new app instance does nothing (current situation) or opens a new window. I think this has to do with different flags for `gio::Application`, have you already experimented with this? I think it's already possible to pass a custom application to `RelmApp` for testing this.

**Comment by euclio** [comment]
I'll investigate this soon.
