### ISSUE TITLE
Update gtk4 dependency to 0.6.0

### ISSUE THREAD

**Issue by liferooter** [Relm4/Relm4#410]
Currently the latest version of `relm4` crate depends on `gtk4` crate of version `0.5.0`. But the latest version of `gtk4` crate is `0.6.1`. So I can't use the latest version of `gtk4` with `relm4`. It's not good. I suggest you to update dependency version. I understand that updating dependency to incompatible version is a breaking change, so you have to also update your own version to `0.6.0`.

**Comment by AaronErhardt** [comment]
Good point. Relm4 follows the gtk-rs version and unfortunately, 0.5 took quite some time to finish. The question is how we proceed from here. I think we could maybe create a "next" branch to start off the development of 0.6 and publish a early alpha version of it on crates.io which would be just 0.5 with updated dependencies. What do you think?

**Comment by liferooter** [comment]
Looks great for me

**Comment by AaronErhardt** [comment]
As a quick update, the "next" branch is now used for developing Relm4 0.6 and has already upgraded gtk-rs (so you can already target it with cargo if you want). I will soon release an early version of 0.6 on crates.io once [a regression regarding our tests](https://github.com/gtk-rs/gtk-rs-core/issues/1014) has been sorted out.

**Comment by AaronErhardt** [comment]
`0.6.0-alpha.1` is published on crates.io :rocket:
