### ISSUE TITLE
RelmApp API for using MessageBroker with the top-level Component

### ISSUE THREAD

**Issue by azymohliad** [Relm4/Relm4#411]
Hey! So [as we discussed in Matrix room](https://matrix.to/#/!DlltQISlgRGacjtFQD:matrix.org/$pJkYD1Sle6P9PZHF9dT_E6DkErlTQUiImOvb8ZVe2rs?via=matrix.org&via=gnome.org&via=the-apothecary.club), I'm trying to add builder pattern to `RelmApp` to allow message broker to be attached to the top-level component.

I guess there's no much point to use proper builder pattern with `RelmAppBuilder` here versus adding modifier methods to `RelmApp` because it behaves like a builder itself: simply stores data until consumed when run. Ideally, I hoped it would allow it to use it like this:

```rust
RelmApp::new<Model>(app_id)
    .with_args(&some_args)
    .with_broker(&some_broker)
    .as_async(true)
    .run()
```

But there are a few issues here.

First, to store those optional fields `RelmApp` would need to be generic over component but also over args type, which for sync component only could look like this:

```rust
pub struct RelmApp<'broker, 'args, C: Component, S: AsRef<str>> {
    app: gtk::Application,
    broker: Option<&'broker MessageBroker<C>>,
    args: Option<&'args [S]>,
}
```

And when `with_broker` and `with_args` aren't used (and I assume this is most of the time), Rust would require to specify those generic types explicitly, which doesn't make much sense when those aren't used.

Second, it seems to be quite hard and probably unreasonable to make it properly generic over both sync and async components, and it looks easier to stick to separate `run<C: Component>()` and `run_async<C: AsyncComponent>()` methods. MessageBroker is implemented for sync only, but I assume it should be easy to add it to async too. It looks like `MessageBroker` doesn't use anything besides `Input` type from the `Component` it is generalized over, so maybe it can rather be generalized over message type? And then if the same message broker struct could be reused for async, then I guess `RelmApp` could be generic over message type and store the broker.

But overall, I'm really not sure how to proceed. Just adding `run_with_broker` and `run_with_args_and_broker` methods doesn't seem like such a bad idea anymore, but only until message broker is implemented for async.

What are your thoughts?

**Comment by AaronErhardt** [comment]
I'll have a closer look at this tomorrow. Maybe using `dyn` or even converting it to `&str` directly would at least help with getting rid of generics for the args and the additional lifetime.

**Comment by azymohliad** [comment]
Yes, storing args as `Vec<String>` and changing `MessageBroker`'s generic to message type itself actually made it quite doable. Message type is always derived automatically from component type, so all of the following works as expected:

```rust
RelmApp::new(app_id).with_args(&some_args).with_broker(&some_broker).run::<SomeComponent>();

RelmApp::new(app_id).run::<SomeComponent>();

RelmApp::new(app_id).run_async::<SomeAsyncComponent>()
```

I made a draft [PR](https://github.com/Relm4/Relm4/pull/412), but haven't properly tested it yet.
