### ISSUE TITLE
Worker cannot modify CommandOutput.

### ISSUE THREAD

**Issue by songww** [Relm4/Relm4#429]
Some places should use worker semantics, but cannot be used.

**Comment by AaronErhardt** [comment]
I don't quite understand, can you please elaborate?

**Comment by AaronErhardt** [comment]
The `Worker` trait is another convenience sub-trait of `Component`. In Relm4's source, the actual requirement for worker components is that they have the unit type as `Widgets`. So if you need commands, you can actually use the `Component ` trait.

The reason why worker don't have proper access to commands yet is that this didn't seem to be useful for the majority of users. And unless [associated type defaults](https://github.com/rust-lang/rust/issues/29661) become available, I didn't want to bother to specify the `CmdOutput` type when implementing workers. This does not mean that this was the correct decision, but that's how things are implemented for now.

**Comment by songww** [comment]
Yes, this issue is just to document the problem.

**Comment by AaronErhardt** [comment]
The worker documentation has been updates now: https://github.com/Relm4/Relm4/commit/e99321303b729a97d642b7e3ce49f5644d56beb6
