### ISSUE TITLE
Add a way to install RelmActions at app level

### ISSUE THREAD

**Issue by nahuelwexd** [Relm4/Relm4#431]
Otherwise, the only way to install actions at app level is the classic GIO API, and this API is not compatible with the `menu!` macro.

**Comment by AaronErhardt** [comment]
Is this what you're looking for: https://github.com/Relm4/relm4-template/blob/main/src/main.rs?

**Comment by nahuelwexd** [comment]
It would be, but it was deprecated since GLib 2.32: https://docs.gtk.org/gio/method.Application.set_action_group.html

**Comment by AaronErhardt** [comment]
Thanks for letting me know. `ActionMap` looks a lot better than the previous API, actually. I think this should be something that should be fixed until 0.6 is released (which is currently developed on the "next" branch).

Would you mind sending a PR? I'm currently working on other things, so it might take some time before I can look into this.
