### ISSUE TITLE
How to get Child component to notify Parent component that it can't continue with initialization 

### ISSUE THREAD

**Issue by adhadse** [Relm4/Relm4#465]
So, I have one parent component that is supposed to load multiple child components, kinda like Factory but I'm keeping it simple here. These child components are independently responsible for doing some task that can fail midway and you can't load the model of the child component. 

For example:
1. Parent component does background tasks connecting to a server etc, setup other things.
2. Child component fetches an image from server and load it.

In such a scenario, it would be ideal to let the parent component to be notified similar to Option enum to return an error to Parent component if image fetch gives 404 and let the parent component skip it. 

The only solution currently I am thinking of is to let parent component do the heavy lifting and the child component will just display it if the model is correctly built. 
Cons:
- This complicates the responsibility of Parent component, it's purpose is mixed? A child component should have just fetched it and loaded.

**Comment by AaronErhardt** [comment]
Are you using regular components or asynchronous components?

Maybe you can use this solution:

```rust
// The child component
struct ComponentModel {
    // ...
}

impl ComponentModel {
    // Optional initialization
    fn init() -> Option<Self> {
        //
    }
}

impl Component for ComponentModel {
    // Pass the entire model as init parameter
    type Init = Self;
    // ...
}

    // Then in the parent component:
    fn init(/* ... */) -> ComponentParts<Self> {
        // ...

        // Only launch the component if the initialization works
        if let Some(child) = ComponentModel::init() {
            model.child = Some(ComponentModel::builder().launch(child).detach());
        }

        // ...
    }
```

Please let me know if that works for you :)

**Comment by adhadse** [comment]
The thing is my child component i.e., `ComponentModel`'s `init()` method returns `ComponentParts<Self>`. So I don't think this would work.

**Comment by adhadse** [comment]
Ah, got it. But then what about the child components's `view_output!()` ? Where does that fit in? 🤔

**Comment by AaronErhardt** [comment]
Something like this:

```rust
fn init(init: Self, root: &Self::Root, sender: ComponentSender<Self>) -> ComponentParts<Self> {
    let model = init;

    let widgets = view_output!();

    ComponentParts {
        model,
        widgets,
    }
}
```

**Comment by AaronErhardt** [comment]
Yes, that is one solution. You could also have a separate init type that contains the result of all fallible operations and then use the `Component::init()` for initializing the model in an infallible manner. Often, it is enough to just pass `Self` as `Init` parameter though.

Btw. it was probably a bad idea to call the custom method `init()` because that could lead to collisions, so you should probably choose another name.
