### ISSUE TITLE
Using template_child multiple with same name multiple times doesn't work

### ISSUE THREAD

**Issue by siddharthroy12** [Relm4/Relm4#476]
If a template with template child is using multiple times then the template child of previous template merges to template child of next template.

Example template:
![image](https://github.com/Relm4/Relm4/assets/46083528/1cb0e6d5-64a2-4089-8db1-f2d0c25a932c)

Usage:
![image](https://github.com/Relm4/Relm4/assets/46083528/4cde773b-e39d-4b74-a106-13c7e617124f)

Expected two buttons vertically which I got but the contents of first button got appended to the second button

https://github.com/Relm4/Relm4/assets/46083528/07c0577f-c341-4c16-b815-994441bedc3a

**Comment by AaronErhardt** [comment]
Can you confirm whether the `fix-template-children` branch (see #477) fixes your problem?

**Comment by siddharthroy12** [comment]
It says cannot find adw in relm4

![image](https://github.com/Relm4/Relm4/assets/46083528/3cb3ed91-9144-410d-8ea1-88e593fda176)

**Comment by siddharthroy12** [comment]
This worked!

**Comment by AaronErhardt** [comment]
Nice! I'll merge the PR and in a couple of days, a new release should be out with the fix included.
