### ISSUE TITLE
Importing Relm4 macros causes many spurious Rust compiler warnings

### ISSUE THREAD

**Issue by chriskilding** [Relm4/Relm4#483]
When using the Relm4 macros (`view!`, `menu!` etc.) it is normally necessary to import them, or compilation will fail. But strangely, if you do import them you then get an 'unused import' warning for each one:

```
warning: unused import: `relm4_macros::view`
 --> src/components/foo.rs:4:5
  |
4 | use relm4_macros::view;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

As you can imagine this adds up to a lot of spurious warnings across any typical Relm4 codebase.

Is there a reason that this is happening?

**Comment by AaronErhardt** [comment]
If you use those macros inside of the `relm4::component` attribute macro those macros are already included there and not the same as a manual macro invocation.

> As you can imagine this adds up to a lot of spurious warnings across any typical Relm4 codebase.

This shouldn't happen and you'd be the first to report a problem regarding this. I don't see a problem here, unless you have to import those macros to make your code work and it still throws a warning.

**Comment by chriskilding** [comment]
Aha - figured it out.

All my uses of those macros are now indeed inside the `relm4::component` attribute, so I tried taking away the imports and it compiled fine.

In the end the problem was that while it was valid Rust, the IntelliJ Rust plugin is not yet smart enough to know that these macros are implicitly available inside the `relm4::component` attribute, so it was giving me `Unresolved reference` errors.  So chalk this one up to a bug in the IntelliJ Rust plugin; hopefully they'll fix that as time goes on.
