### ISSUE TITLE
No way to reuse local widget in `view!` macro

### ISSUE THREAD

**Issue by Skaldebane** [Relm4/Relm4#487]
Hi there! While coding my app, I needed to implement a `gtk::SearchBar` in a component.

In most GTK widgets that take one child, the `set_child` method will be the only thing you need to get things up and running.

However, for a `SearchBar`, you have to call `set_child` with a `gtk::Entry` (or any of its descendants) and then call `connect_entry` with a reference to the exact same widget.

Writing this with only gtk4-rs manually is quite simple, bind the `gtk::Entry` to a variable, then pass a reference to it to both functions.

In the `view!` macro, however, it's not possible to do this currently without building the entire `gtk::SearchBar` manually.

Starting with a naive approach, let's create the `gtk::SearchEntry` and give it a name `search_entry` as part of calling `set_child`:

```rust
view! {
    #[root]
    gtk::SearchBar {
        #[wrap(Some)]
        set_child: search_entry = &gtk::SearchEntry {
            // code here....
        }
    }
}
```

Now let's try to use the name we defined...
```rust
view! {
    #[root]
    gtk::SearchBar {
        #[wrap(Some)]
        set_child: search_entry = &gtk::SearchEntry {
            // code here....
        },
        
        #[local]
        connect_entry = &search_entry,
    }
}
```

Here, I set `connect_entry` to the `search_entry`, and I thought that using `#[local]` should just work...

Well...
```
error[E0416]: identifier `search_entry` is bound more than once in the same pattern
  --> src/ui/search_bar.rs:38:30
   |
38 |             connect_entry = &search_entry -> gtk::SearchEntry,
   |                              ^^^^^^^^^^^^ used in a pattern more than once


error[E0124]: field `search_entry` is already declared
  --> src/ui/search_bar.rs:20:20
   |
20 |    #[relm4::component(pub)]
   |  _____________________^
   | | ____________________|
   | ||
21 | || impl SimpleComponent for SearchBarModel {
22 | ||     type Init = SearchBarModel;
23 | ||     type Input = SearchBarInput;
...  ||
32 | ||             #[wrap(Some)]
33 | ||             set_child: search_entry = &gtk::SearchEntry {
   | ||_______________________________________________________- `search_entry` first declared here
...  |
37 | |              #[local]
38 | |              connect_entry = &search_entry -> gtk::SearchEntry,
   | |______________________________________________________________^ field already declared
```

It seems like using `#[local]` doesn't work here.

What I tried so far:
+ **Using `#[local_ref]`:** Same error as using `#[local]`
+ **Defining the widget in the root of the `view!` macro**: Using `search_entry = gtk::SearchEntry { ... }`, yet the same problem happnes. Trying to reuse it from within the `gtk::SearchBar` even once results in the same error.
+ **Defining the widget in the `init` function:** Using the `relm4::view!` macro, just as I already do with factories. Using it once works, but trying to use it twice fails with the same error, for both `#[local]` and `#[local_ref]`.

Now I just create the entire `gtk::SearchBar` widget in the body of the `init` function inside the `relm4::view!` macro, defining the `search_entry` before `search_bar` and then using it as many times as I want without issues. I wish this was the case with the normal `view!` macro.
```rust
view! {
    #[root]
    adw::Bin {
        #[local]
        search_bar -> gtk::SearchBar,
    }
}

fn init(init: Self::Init, root: &Self::Root, _sender: ComponentSender<Self>) -> ComponentParts<Self> {
    let model = init;
    relm4::view! {
        search_entry = gtk::SearchEntry {
            // code here....
        },
        search_bar = gtk::SearchBar {
            #[wrap(Some)]
            #[local]
            set_child = &search_entry,

            #[local]
            connect_entry = &search_entry,
        }
    }
    let widgets = view_output!();
    ComponentParts { widgets, model }
}
```

Is there a better, more natural approach? Or am I just missing something obvious? In case there's really no way to do this now, I'd love to see something like `#[local]` or `#[local_ref]` that allows reusing the reference all within the `view!` macro.

And thanks for this brilliant crate!

**Comment by AaronErhardt** [comment]
I do not understand why you need to use `#[local]`. Please let me know if the book is not clear about this, but the `#[local]` and `#[local_ref]` attributes are supposed to be used for widgets created manually in `init()`. Widgets created in the view macro are already initialized and in scope, so you can use `:` to assign them to certain properties. 

I think this code should work for you:

```rust
view! {
    #[root]
    gtk::SearchBar {
        #[wrap(Some)]
        set_child: search_entry = &gtk::SearchEntry {
            // code here....
        },
        
        connect_entry: &search_entry,
    }
}
```

**Comment by Skaldebane** [comment]
My bad, I learnt about the `#[local]` thing in using factories, so I just used it without fully understanding its purpose. I thought it was used whenever using a widget from a "variable".

As for the book, the "Component macro reference" page doesn't mention `#[local]` and `#[local_ref]` (and for that matter, the difference between them, since I find that they work interchangeably most of the time), which is where I'd expect them (and every other feature of the macro) to be thoroughly explained, aside from the brief introductions to them in other parts of the book.

Aside from that, my issue is solved and your code works perfectly, thanks a lot!
