### ISSUE TITLE
Visuals not going back

### ISSUE THREAD

**Issue by mskorkowski** [Relm4/Relm4#51]
Today while I was playing with components example (`cargo run --example components --package=relm4-examples`) if found an issue where toggle buttons are not going back.

If I click buttons slowly click button-pause-click other button-pause-click other button-pause... then all works fine. I've wasted for this test 5min to check if all is working fine.

![Screenshot from 2021-11-05 23-23-40](https://user-images.githubusercontent.com/90662755/140585632-a887c2c2-b43f-4ebe-b181-c7da095dae4e.png)
![Screenshot from 2021-11-05 23-24-24](https://user-images.githubusercontent.com/90662755/140585636-dee57533-4235-4017-b214-06c475297f7a.png)
![Screenshot from 2021-11-05 23-24-41](https://user-images.githubusercontent.com/90662755/140585637-58d35a4e-1591-456a-8af7-b7a0dada3d9d.png)

But when I start clicking fast on buttons. Sometimes clicking twice. Go back and forth between them. In a few seconds I'm ending up with

![Screenshot from 2021-11-05 23-25-34](https://user-images.githubusercontent.com/90662755/140585735-282d4770-1fec-422d-b6ed-12297a25ca9d.png)
![Screenshot from 2021-11-05 23-25-56](https://user-images.githubusercontent.com/90662755/140585736-d1004674-a351-4e4b-ae21-77161a5c50cd.png)
![Screenshot from 2021-11-05 23-26-17](https://user-images.githubusercontent.com/90662755/140585737-7d298a3b-2925-4b75-86db-df27b866d82f.png)
![Screenshot from 2021-11-05 23-26-30](https://user-images.githubusercontent.com/90662755/140585738-5fcdcbcd-7914-466f-8834-a3875ab5da51.png)

Something similar happens when I scroll fast. In list example (`cargo run --example list --package=relm4-examples`) if I use a mouse wheel to scroll over the minimum position of the list I get this nice gtk glow at the top hinting hey, that's it (I can't capture it since it will disappear before I can take a screen shot).

If I use a mouse wheel to go fast over the minimum position of the list, then the glow will become permanent. Using mouse wheel I can select the level of the hint and now I know that there are 6 of them (including lack of hint). What's more if ui ends in a state when the hint is permanent on top then it's also in permanent on bottom.

![Screenshot from 2021-11-05 23-27-24](https://user-images.githubusercontent.com/90662755/140588102-a3a361af-8535-43e4-b09f-10d289e73adc.png)
![Screenshot from 2021-11-05 23-28-08](https://user-images.githubusercontent.com/90662755/140588104-6c8da696-6c7c-4089-95ea-e2421d84fa04.png)
![Screenshot from 2021-11-06 00-10-23](https://user-images.githubusercontent.com/90662755/140588106-a8d795ac-644a-4dcd-969f-7264a0482e28.png)

Last image was captured with focus being on input after typing a few letters

![Screenshot from 2021-11-05 23-29-01](https://user-images.githubusercontent.com/90662755/140588105-054b9c25-60ee-4cfd-9b3b-ead2ab2427f6.png)

**Comment by AaronErhardt** [comment]
I don't think this is related to Relm4 but rather an issue in GTK4. Even when I remove all the signal handling from the example I can still recreate this issue. Also the toggle buttons are in one group which means that GTK takes care that only one is active at the time or that's at least how that should work.

**Comment by mskorkowski** [comment]
I'll try to prepare the examples in pure gtk-rs and c somewhere during this week to report it upstream.
