### ISSUE TITLE
[Ergonomics/performance] Can we avoid storing the SimpleComboBox variants twice 

### ISSUE THREAD

**Issue by marmistrz** [Relm4/Relm4#540]
Currently only the index is returned, but this requires the variants to be stored _twice_: once in the `SimpleComboBox` and once in the closure. (both `launch` and `forward` consume the component, so it's impossible to use it in the `forward` closure).

However, returning `E` would require `E: Clone` and returning `&E` gets us into lifetime troubles.

**Comment by AaronErhardt** [comment]
You can just access the `variants` field if you need to access the variants after the component has been launched. All other options will cause lifetime issues. For most usecases [`get_active_elem`](https://docs.rs/relm4-components/0.7.0-beta.1/relm4_components/simple_combo_box/struct.SimpleComboBox.html#method.get_active_elem) should be convenient, but if you describe your usecase, we might figure out a better/new API for you.

**Comment by marmistrz** [comment]
Em, I can't just access the `variants` field: let's try to modify the code from the combo_box example and try to output the string instead of the index:
```
        let combo = SimpleComboBox::builder().launch(SimpleComboBox {
            variants: LANGS.to_vec(),
            active_index: Some(default_idx),
        });
        let combo = combo.forward(sender.input_sender(), |idx| {
            let name = combo.model().variants[idx];
            AppMsg::ComboChanged(idx)
        });
```

I can't use the `SimpleComboBox` struct in the closure because it was consumed by `launch`. Trying to use `model` correctly triggers the borrow checker. I can't move the combo _both_ into the closure and into `forward`.

**Comment by AaronErhardt** [comment]
Why would you even need the combo box in the `forward` closure? You can just access the combo box in `update()` from the model of the outer component. I see that it would be convenient in your case, but Relm4 has to make the borrow checker happy internally as well, and I don't see an easy to solution to make the model available in the `forward` closure.

**Comment by marmistrz** [comment]
I see, thanks. I'll try to update the example to make it work.
