### ISSUE TITLE
How to trigger an update without user interaction?

### ISSUE THREAD

**Issue by bistace** [Relm4/Relm4#542]
Hello,
I am trying to create a chess engine that will be used to train an AI to play chess against other engines. I am trying to use relm4 to display the state of the board.

Here's what I did so far:
  - create an empty board struct and pass it to the model
  - display an empty board in the main window

I have some difficulties seeing how to mutate the board and trigger an update without the user interacting with the window (there is no button or anything, it is just used to display the state of the board). I have looked at components and workers but it seems that they still need an input message to trigger some actions.

Could you please point me in the right direction?

**Comment by AaronErhardt** [comment]
Have you worked with channels in Rust before? It's really as simple as cloning a sender (which you can get with `sender.input_sender().clone()`) and moving it into a closure that is called regularly (for example with [`timeout_add`](https://gtk-rs.org/gtk-rs-core/git/docs/glib/source/fn.timeout_add.html). You can also spawn a thread instead. 

Alternatively, you can use built-in functionality of Relm4, such as commands. You can spawn a command that, for example, runs some code and once the calculation is finished sends a command input message to your component.

**Comment by bistace** [comment]
Oh thank you, I see how to do it now!
