### ISSUE TITLE
Relm4 book - link to examples broken

### ISSUE THREAD

**Issue by PJaros** [Relm4/Relm4#556]
The [introduction page](https://aaronerhardt.github.io/relm4-book/book/introduction.html) has a link "relm4-examples crate" which is broken.

It links to https://github.com/AaronErhardt/relm4/tree/main/relm4-examples but should probably link to https://github.com/Relm4/Relm4/tree/main/examples

![grafik](https://github.com/Relm4/Relm4/assets/1235182/3d818d73-c37c-47ae-9875-c069d5dcf489)

**Comment by AaronErhardt** [comment]
You're using a very old version of the book. The book has been hosted at https://relm4.org/book/stable/ for years now. Yet, it would be interesting for me to know how you found this old link, so we can remove it (or even delete the old book entirely to avoid confusions like this).
