### ISSUE TITLE
Unable to hide an application window

### ISSUE THREAD

**Issue by hwittenborn** [Relm4/Relm4#558]
I have a use case for a file synchronization program I'm working on (see [hwittenborn/celeste](/hwittenborn/celeste)). In that program, there's a main window that shows up while syncing files, but if a user hasn't logged in at all yet, a login window gets displayed instead.

I'd like to implement this by having an `AppModel` and `LoginModel` struct. When the user still needs to log in, I'd like the window for `AppModel` to be hidden, but I can't figure out how I'd do it in Relm4.

Here's a test case that demonstrates the problem:

```rust
use relm4::prelude::*;
use adw::prelude::*;

struct AppModel;

#[relm4::component]
impl SimpleComponent for AppModel {
    type Input = ();
    type Output = ();
    type Init = ();

    view! {
        adw::ApplicationWindow {
            set_visible: false,

            adw::HeaderBar {}
        }
    }

    fn init(
        init: Self::Init,
        root: &Self::Root,
        sender: ComponentSender<Self>,
    ) -> ComponentParts<Self> {
        let model = Self;
        let widgets = view_output!();
        ComponentParts { model, widgets }
    }
}

fn main() {
    let app = RelmApp::new("com.example.Testing");
    app.run::<AppModel>(());
}
```

I also made an example using libadwaita directly to make sure I wasn't just calling an incorrect function or something, but it indeed works fine:

```rust
use adw::{Application, ApplicationWindow, prelude::*, gio, glib::{self, MainContext, Priority}};
use std::{time::Duration, thread};

fn main() {
    let app = Application::builder()
        .application_id("com.hunterwittenborn.Testing")
        .build();
    app.connect_activate(|app| {
        let window = ApplicationWindow::builder()
            .application(app)
            .title("Hello, World!")
            .build();
        window.present();

        // Close the window after waiting two seconds.
        let (sender, receiver) = MainContext::channel(Priority::default());
        gio::spawn_blocking(move || {
            thread::sleep(Duration::from_secs(2));
            sender.send(()).unwrap();
        });
        receiver.attach(None, move |_| {
            window.set_visible(false);
            glib::ControlFlow::Continue
        });
    });
    app.run();
}
```

Is there any way to get what I'm wanting to work with Relm4?

**Comment by AaronErhardt** [comment]
Yeah, `set_visible: false,` is not going to help because `RelmApp::run` will immediately do the opposite: https://docs.rs/relm4/latest/src/relm4/app.rs.html#100

My suggestion would be to add a new method to the RelmApp builder pattern. Something like `app.start_visible(false).run::<AppModel>()`. What do you think?

**Comment by hwittenborn** [comment]
I was thinking Relm might've been doing something internally, thanks for the confirmation @AaronErhardt.

> My suggestion would be to add a new method to the RelmApp builder pattern. Something like `app.start_visible(false).run::<AppModel>()`. What do you think?

What about this:

If the user has `set_visible` set to any value in the root element of `view! { ... }`, then just don't run `window.set_visible(true)`.

I'd think that'd work fine and make sense logically (as long as it's documented), as if the user has `set_visible` defined in their code, they probably doesn't want Relm to override their choice.

Regarding how `RelmApp` would know about the `set_visible` choice, I think having something like `const AUTO_SHOW: bool` on the `Component` trait definition would work well. Then people who don't use the `view! {}` macro would be able to declare that they don't want the window automatically opened too.

What do you think about all that?

**Comment by AaronErhardt** [comment]
I've found an easy solution: Setting the visibility to "true" before the launch allows you to override the value during the launch of the component. Can you checkout the branch of #559 to check whether this works for you?

**Comment by hwittenborn** [comment]
Hey @AaronErhardt, I just wanted to send a message that I'm still trying to get this all tested out properly. I'm almost done with testing everything locally on my machine, but I'll let you know once I get it all finished up.

**Comment by hwittenborn** [comment]
I just finished testing this all up @AaronErhardt, and at least on usage from `AsyncComponent`, it looks like the window pops up until `AsyncComponent::init` finishes:

```rust
use std::{thread, time::Duration};
use relm4::{
    component::{
        AsyncComponent,
        SimpleAsyncComponent,
        AsyncComponentSender,
        AsyncComponentParts,
        AsyncController,
        AsyncComponentController
    },
    prelude::*,
    adw::prelude::*,
    tokio
};

struct AppModel;

#[relm4::component(async)]
impl SimpleAsyncComponent for AppModel {
    type Input = ();
    type Output = ();
    type Init = ();

    view! {
        adw::ApplicationWindow {
            set_visible: false
        }
    }

    async fn init(
        init: Self::Init,
        root: Self::Root,
        sender: AsyncComponentSender<Self>,
    ) -> AsyncComponentParts<Self> {
        relm4::spawn_blocking(|| thread::sleep(Duration::from_secs(2))).await.unwrap();
        let model = AppModel;
        let widgets = view_output!();
        AsyncComponentParts { model, widgets }
    }
}

fn main() {
    let app = RelmApp::new("com.example.Testing");
    app.run_async::<AppModel>(());
}
```

In my local testing the window stayed visible for two seconds and then disappeared.

Removing the `relm4::spawn_blocking(|| thread::sleep(Duration::from_secs(2))).await.unwrap()` call makes the window not appear, but I'm not sure if that's due to it just closing really fast or not.

**Comment by AaronErhardt** [comment]
> I just finished testing this all up @AaronErhardt, and at least on usage from AsyncComponent, it looks like the window pops up until AsyncComponent::init finishes

Using [init_loading_widgets](https://docs.rs/relm4/latest/relm4/component/trait.AsyncComponent.html#method.init_loading_widgets) would fix that. I don't know if there's a better solution though. The only other simple fix I can think of right now is the [initial suggestion](https://github.com/Relm4/Relm4/issues/558#issuecomment-1765176616). The timing makes it really tricky because async components can initialize delayed.

**Comment by hwittenborn** [comment]
I'm not positive how everything works internally, but would it not be be possible to avoiding showing anything until `init` finishes running?

If it adds a signification amount of complexity I think an `app.start_visible(false)` function would work well too though. I was mostly just wanting to see what other options were out there, but from the looks of it it seems like the latter may be the most straightforward.

**Comment by AaronErhardt** [comment]
> I'm not positive how everything works internally, but would it not be be possible to avoiding showing anything until init finishes running?

This is possible, but would require passing the information down to the component runtime. It wouldn't be terribly difficult to add this, but the question is whether this new behavior would be better. After the first fix, only async components are affected by this issue and I think most apps would like to have their window presented immediately to show a loading animation. If we change this to after launch, this would not happen by default.

So instead of changing from one potentially unexpected default to another potentially unexpected default, I suggest we actually implement a method on `RelmApp` (as I have done in the latest commit in the PR) to set the behavior explicitly if needed.

What do you think?

**Comment by hwittenborn** [comment]
> ...the question is whether this new behavior would be better. After the first fix, only async components are affected by this issue and I think most apps would like to have their window presented immediately to show a loading animation. If we change this to after launch, this would not happen by default.

Would it work fine to just hide the window if `init_loading_widgets` is `None`, and then show it if not? Or would there still be a problem with that too?

> I suggest we actually implement a method on `RelmApp` (as I have done in the latest commit in the PR) to set the behavior explicitly if needed.

I can confirm that's working just fine locally, at the least it would be a more than suitable workaround until more discussion on the topic could be done.
