### ISSUE TITLE
`menu_actions_and_settings` example crashes on macOS 14.1 ARM

### ISSUE THREAD

**Issue by dominikwilkowski** [Relm4/Relm4#571]
Looks like the example `menu_actions_and_settings` pulled today from `main` as is crashes:
<img width="1045" alt="image" src="https://github.com/Relm4/Relm4/assets/1266923/b893ff70-9b64-492b-8beb-520886daced1">

<img width="372" alt="image" src="https://github.com/Relm4/Relm4/assets/1266923/f476f511-25d0-4ead-bfaf-31037a43cd01">

**Comment by AaronErhardt** [comment]
This is expected as (only) this specific example requires additional setup: https://github.com/Relm4/Relm4/tree/main/examples#setup

The code behind it is not very well maintained however, and is likely going to be removed because there are already alternatives for archiving the same result.
