### ISSUE TITLE
Increase flexibility of `Alert` component

### ISSUE THREAD

**Issue by hwittenborn** [Relm4/Relm4#575]
I'm wanting to use the `Alert` component from `relm4_components`, but it currently isn't flexible enough for my needs.

If I were to use the `Alert` component, I'd need the following functionality in it:

- The ability to only have one button. I have a use case where I'm wanting to show an error to the user, and only have them click an `Ok` button.
- The ability to manually hide the widget. I have another use case where the user will have a `Cancel` button on the `Alert` component to quit a task, but I also want to close it manually if that task finishes before they do such.
- The ability to change the text on any of the widget's settings after creation. I'm wanting to store this widget as part of it's parent widget, but I won't know the text I'm displaying to the user until a later point in my app's execution cycle (I'll be displaying a `Logging in to {cloud provider}` message as part of [hwittenborn/celeste](https://github.com/hwittenborn/celeste)).

I'm willing to submit a PR for these changes, I'm just seeing if it's something y'all would be open to accepting.

**Comment by hwittenborn** [comment]
I also have a function in my codebase that doesn't use Relm4, but it's basically the above use case with the addition of a custom GTK widget that I use to show a codeblock (specifically I'm using [`MessageDialog::set_extra_child`](https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/stable/latest/docs/libadwaita/prelude/trait.MessageDialogExt.html#method.set_extra_child)).

I don't know how "Relm4-esque" that would be to make it accept a widget in `AlertSettings`, but I can't think of any better ways of doing it without making `Alert` a template widget.

**Comment by AaronErhardt** [comment]
Sounds like a good idea. 

> I don't know how "Relm4-esque" that would be to make it accept a widget in AlertSettings, but I can't think of any better ways of doing it without making Alert a template widget.

It should probably be optional, but otherwise allowing to pass a widget should be fine.
