### ISSUE TITLE
`transient_for` errors in child component

### ISSUE THREAD

**Issue by nazar-pc** [Relm4/Relm4#584]
I have the following hierarchy: `App > Component` and `Component::init` crates `OpenDialog`.

The issue is that in this case `transient_for(&root)` results in this:
```
2023-12-09T12:40:47.898031Z ERROR relm4::component::sync::builder: Couldn't find root of transient widget
```

The reason is that `Component` wasn't yet added to window, we're still building it. I didn't find clearer solution than to pass `Window` down as `Component::Init`, but it feels like that error shouldn't happen and `OpenDialog` should be able to attach to window once window is available even if is not available during construction.

**Comment by AaronErhardt** [comment]
The way Relm4 handles this is the following:

1. Store code for `transient_for` as closures
2. Wait for all the main component to finish initialization (which usually initializes most child components)
3. Call all stored closures

Yet if you call `transient_for` later on, the code won't be delayed. This means that the widget has no root yet when `transient_for` is called. One solution for that would be to add the widget of the child components before calling `transient_for` on the component builder.

This is - like many things in Relm4 - a problem of ordering certain operations. However, we could try to solve this by executing the `transient_for` code as an asynchronous task. This way, it should only run once the function in which `transient_for` was called from has returned, which should mean that the widget should have been added to window already...

Would you mind testing a branch with a potential fix for your issue?

**Comment by nazar-pc** [comment]
I can test a potential fix, sure
