### ISSUE TITLE
Just tested, weird behavior

### ISSUE THREAD

**Issue by ftaiolivista** [Relm4/Relm4#597]
[relm4.webm](https://github.com/Relm4/Relm4/assets/150721/aeef4fe4-32ab-452b-9ae4-625653efecfb)

[Cargo.lock.txt](https://github.com/Relm4/Relm4/files/13921559/Cargo.lock.txt)

local/gtk4 1:4.12.4-1

**Comment by AaronErhardt** [comment]
I know it looks odd, but this behavior is actually expected. The code sets the margin of the main window and the only thing behind the window is other apps. It's not really a useful feature, but the example only tries to show how you can set properties and margin is a property that's easy to observe.
