### ISSUE TITLE
relm4@v0.7.0-rc.1 depends still on relm4-macro@v0.7.0-alpha.1

### ISSUE THREAD

**Issue by patinu** [Relm4/Relm4#613]
After updating relm4 from v0.7.0-beta.2 to v0.7.0-rc.1 in my project I got an error message about a failure of implementing the trait `FactoryComponent` by the macro `relm4::factory`. That was because of the package dependency entry in the file `Cargo.lock` for `relm4-macros` at version `v0.7.0-beta.2`. Removing this entry solved the problem. Cargo installed the right version `v0.7.0-rc.1` of `relm4-macros` automatically.

But I think there is still the problem that `relm4@v0.7.0-rc.1` depends on `relm4-macros@0.7.0-alpha.1` but not `relm4-macros@0.7.0-rc.1`. See [Cargo.toml](https://github.com/Relm4/Relm4/blob/c3ad44e5ba917c0d648c2ba5324e14afe636d464/relm4/Cargo.toml#L49C29-L49C42)

The pull request #564 changed some signatures of different traits. Using an old version of `relm4-macros` implements these traits in a wrong way. Updating relm4 from v0.7.0-beta.2 to v0.7.0-rc.1 keeps an old version of relm4-macros.

**Comment by AaronErhardt** [comment]
Thanks for the report! Fortunately, this should be fixed now with the 0.7 stable release.
