### ISSUE TITLE
All versions after 0.6.2 include libadwaita by default

### ISSUE THREAD

**Issue by eppixx** [Relm4/Relm4#620]
After the version 0.6.2 all build apps use libadwaita even when not using the feature flag `libadwaita`. This causes the styling of build apps to change which is in my case not desired as my app is not targetting Gnome.

Using `default-features =false` still includes it.

**Comment by AaronErhardt** [comment]
Mhh, that's interesting. We didn't change anything big other than version numbers in our README. And libadwaita still has `optional = true`: https://github.com/Relm4/Relm4/blob/main/relm4/Cargo.toml#L41

Do you have an idea what causes the problem? Do you use just `relm4` or also other crates like `relm4-components`?

**Comment by eppixx** [comment]
I'm on ElementaryOS and I tested it on simple counter app of the book with only `relm4` and `relm4-components`.

I did some screenshots
![0 6 2](https://github.com/Relm4/Relm4/assets/1942172/d9038d8e-a203-47e6-8184-fd5392901ce9)
![0 8 0](https://github.com/Relm4/Relm4/assets/1942172/1453478a-14d6-4ad3-b78d-5bb7e0296e81)

**Comment by AaronErhardt** [comment]
I've just noticed that relm4-components has libadwaita enabled by default. Unfortunately, I didn't catch it during the review of [this change](https://github.com/Relm4/Relm4/commit/7b37b49486917dac98d86df758403222d9931413).

This should be reverted again, but in the meantime you can use `relm4-components = { version = "0.8", default-features = false }`

**Comment by AaronErhardt** [comment]
I've published relm4-components 0.8.1, which should fix the problem. A quick `cargo update` should do it.

**Comment by eppixx** [comment]
That works. Didn't try using deafult-features on `relm4-components`.
