### ISSUE TITLE
Rewrite `Alert` component to avoid using `MessageDialog`

### ISSUE THREAD

**Issue by hwittenborn** [Relm4/Relm4#645]
Currently, the `Alert` component uses `gtk::MessageDialog`, which causes an issue when you want the body text of the dialog to be center-aligned. The `adw::MessageDialog` centers such text, which - while minor - is desirable by people who want their apps to follow the Adwaita styling.

There's the option of just using `adw::MessageDialog`, which I've currently [mostly implemented](https://github.com/hwittenborn/Relm4/commit/887d03fd06eb7eab34e7ed5fcba1386533e14c40). I'm wondering if it would be better to make a widget that functions the same as `adw::MessageDialog` though, but is just written from scratch with only GTK4. This would allow more flexibility to be put on the widget (such as how text is aligned), and (hopefully) allow backward compatibility to older GTK4 versions.

Any thoughts? I'm open to creating a PR for the Adwaita alert component I've made, but I feel like it's a bit hacky since the Adwaita-based component is largely the same as the GTK4 one. I've also managed to add in support for an extra widget on the Adwaita component, and having a feature mismatch between the two didn't make a ton of sense to me.

**Comment by AaronErhardt** [comment]
> I'm open to creating a PR for the Adwaita alert component I've made, but I feel like it's a bit hacky since the Adwaita-based component is largely the same as the GTK4 one.

I guess this is the best approach. The problem is that if we technically would need 3 versions to satisfy everyone. One for GTK 4.8 or lower, one for GTK 4.10 and higher and one for libadwaita. I think most are going to use libadwaita anyway, so that's likely the most pragmatic approach. I wouldn't put any effort into the GTK versions unless someone needs those (plus the current version will keep working until GTK5 comes out).

**Comment by hwittenborn** [comment]
If a custom widget is made from-scratch in GTK, I think we'd only need to maintain one widget that works across both GTK and Adwaita (as long as the necessary CSS styles are applied to it). I also don't believe there should be any version constraints on GTK4 that would cause issues, considering again that the widget would be made from the ground up.

I know [GTK4 has the `MessageDialog` widget deprecated](https://docs.gtk.org/gtk4/class.MessageDialog.html), but I feel like that's an even better reason to add it to `relm4-components` since it could help bring more people into using `relm4`.

I'll admit that writing a look-alike widget is a bit hacky as well, but I feel like most of the issues would be up-front while implementing the component's code, and then things would be pretty much smooth sailing. If Adwaita were to ever update styling in the `MessageDialog` widget, the styling for the custom component could also be controlled behind features, a toggle in the `Settings` struct of the widget, or something like that.

**Comment by AaronErhardt** [comment]
Sure, it would be nice to have such a widget. If you want to work on that and it turns out to work nicely, I certainly will merge it.
