### ISSUE TITLE
Create a `relm4-css` crate?

### ISSUE THREAD

**Issue by hwittenborn** [Relm4/Relm4#646]
[Adwaita has quite a few CSS classes available for use](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.2/style-classes.html), but it's not extremely clean to have to manually type these out in programs. It's also quite bug-ridden, as typos can't be caught at compile time.

Considering the approach used in `relm4-icons`, I think it could also be good to have a `relm4-css` crate that exposes the CSS classes listed on that website. I can make a PR for this, I was just wondering if there were any thoughts on such before I opened it.

**Comment by AaronErhardt** [comment]
I haven't thought about that before, but sounds like a really nice idea.

**Comment by hwittenborn** [comment]
Closing this up since this got added in #650.
