### ISSUE TITLE
Icons are not correctly displayed

### ISSUE THREAD

**Issue by jdobonb** [Relm4/Relm4#675]
I have tried to make icons work on GTK4 with LibAdwaita without success, the app just renders a triangle with an exclamation mark. A have both tried by my own and with the example `icons.rs`.

I'm on NixOS if that helps.

**Comment by AaronErhardt** [comment]
Might be related to https://github.com/Relm4/icons/issues/12
In general, relm4-icons needs a rework to work reliably ever since the previous mechanism using feature flags was made impossible by decisions of the crates.io team.

**Comment by kutu-dev** [comment]
Any known workarounds? Or a way to force GTK to print logs about why it failed?
