### ISSUE TITLE
Segfault on inspect

### ISSUE THREAD

**Issue by Aworldc** [Relm4/Relm4#687]
Pressing `Ctrl-Shift-d` segfaults the application.

I tried nautilus to make sure it wasn't an issue with my install, but it works fine.

Output: 
```
[nix-shell:~/donkey]$ cargo run
   Compiling thing4 v0.1.0 (/home/allan/donkey)
    Finished dev [unoptimized + debuginfo] target(s) in 2.22s
     Running `target/debug/thing4`

(process:78690): GLib-GIO-CRITICAL **: 19:27:39.546: g_settings_schema_source_lookup: assertion 'source != NULL' failed

(thing4:78690): GLib-GIO-CRITICAL **: 19:28:10.854: g_settings_schema_source_lookup: assertion 'source != NULL' failed
Segmentation fault (core dumped)

[nix-shell:~/donkey]$ 
```

**Comment by Aworldc** [comment]
Project info:

[Cargo.toml.txt](https://github.com/user-attachments/files/17529620/Cargo.toml.txt)
[main.rs.txt](https://github.com/user-attachments/files/17529621/main.rs.txt)
[shell.nix.txt](https://github.com/user-attachments/files/17529622/shell.nix.txt)

**Comment by AaronErhardt** [comment]
Mhh, I wouldn't know any reason why Relm4 would cause this issue. You could maybe try to build a pure gtk-rs example and test that with the inspector.

**Comment by Aworldc** [comment]
Yep, pure gtk-rs doesn't work. not a relm problem
